version: '3.8'

services:
  # TODO: add a frontend client to manage channels.
  database:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.2.2
    container_name: anvil
    ports:
      - "8545:8545"
    entrypoint: ["anvil"] 
    command: ["--host","0.0.0.0","--chain-id","1337","--accounts","15","--balance","300"]
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 5s
      timeout: 5s
      retries: 5

  contract-deployer:
    image: ghcr.io/foundry-rs/foundry:v1.2.2
    container_name: contract-deployer
    depends_on:
      anvil:
        condition: service_healthy
    volumes:
      - ./contract:/app
    working_dir: /app
    command: >
      bash -c "
        forge script script/DeployCustody.s.sol:DeployCustodyScript --rpc-url http://anvil:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast &&
        forge script ./script/DeployFundERC20.s.sol --broadcast --rpc-url http://anvil:8545 --sig 'run(string)' 'test test test test test test test test test test test junk' &&
        forge create --broadcast --optimizer-runs 1000000 --via-ir ./test/mocks/FlagAdjudicator.sol:FlagAdjudicator --rpc-url http://anvil:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --constructor-args true &&
      "

  db-init:
    image: postgres:17.2
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATABASE: ${POSTGRES_DB:-postgres}
      PGHOST: database
      PGPORT: 5432
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        until pg_isready -h database -p 5432 -U ${POSTGRES_USER:-postgres}; do
          echo 'Waiting for database connection...'
          sleep 2
        done &&
        echo 'Checking database...' &&
        
        # Check if token already exists
        TOKEN_EXISTS=$$(psql -h database -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -t -c \"SELECT COUNT(*) FROM assets WHERE token = '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512' AND chain_id = 1337;\" | xargs) &&
        
        if [ \"$$TOKEN_EXISTS\" -eq \"0\" ]; then
          echo 'Seeding database with tokens...' &&
          psql -h database -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -c \"
            INSERT INTO assets (token, chain_id, symbol, decimals) 
            VALUES ('0xe7f1725e7734ce288f8367e1bb143e90bb3f0512', 1337, 'USDC', 6);
          \" &&
          echo 'Database seeded with tokens successfully'
        else
          echo 'Database already seeded, skipping'
        fi
      "
    depends_on:
      database:
        condition: service_healthy
      contract-deployer:
        condition: service_completed_successfully

  clearnode:
    platform: linux/amd64
    image: ghcr.io/erc7824/nitrolite/clearnode:0.0.1-rc.28
    ports:
      - "8000:8000"
      - "4242:4242"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - BROKER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - LOCALNET_CUSTODY_CONTRACT_ADDRESS=0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE
      - LOCALNET_INFURA_URL=ws://anvil:8545
      - CLEARNODE_DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@database:5432/${POSTGRES_DB:-postgres}?sslmode=disable
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

