services:
  database:
    image: postgres:17.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

  db-init:
    image: postgres:17.2
    env_file:
      - .env
    volumes:
      - ./config/migrations/postgres:/migrations
      - ./scripts:/scripts
    command: ["bash", "/scripts/db-init.sh"]
    depends_on:
      database:
        condition: service_healthy

  clearnode:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "4242:4242"
    depends_on:
      database:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
