x-pg-env: &pg-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  PGPASSWORD: postgres

services:
  database:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      <<: *pg-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

  db-init:
    image: postgres:17.2
    environment:
      <<: *pg-env
    volumes:
      - ./config/migrations/postgres:/migrations
      - ./scripts:/scripts
    command: ["bash", "/scripts/db-init.sh"]
    depends_on:
      database:
        condition: service_healthy

  clearnode:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      CLEARNODE_LOG_LEVEL: "info"
      CLEARNODE_DATABASE_URL: postgresql://postgres:postgres@database:5432/postgres?sslmode=disable
      MSG_EXPIRY_TIME: "60"
      CLEARNODE_CONFIG_DIR_PATH: /config
    volumes:
      - ./config/compose/local:/config:ro
    ports:
      - "8000:8000"
      - "4242:4242"
    depends_on:
      database:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
