sequenceDiagram
        actor User
        actor Client
        actor Node
        actor HomeChain
        actor EscrowChain
        Note over HomeChain: User already has a home channel
        Note over Node: Contains user's state with Home Chain 
        Note right of Client: Connected to Node
        User->>Client: async withdraw(blockchainId, asset, amount)

        Client->>Node: GetLastState(UserWallet, asset)
        Note right of Node: GetLastState(userWallet, asset)
        Node->>Client: Returns state
        Note over Client: createNextState(currentState) returns state
        Note over Client: state.setID(CalculateStateID(state.userWallet, state.asset, state.cycleId, state.version))
        Note over Client: GetTokenAddress(blockchainId, asset)
        Note over Client: state.setEscrowToken(blockchainId, tokenAddress)
        Note over Client: GetEscrowChannelID(homeChannelDef, state.version)
        Note over Client: NewTransition(escrowLockT, state.ID(), escrowChannelID, amount)
        Note over Client: state.applyTransitions(transtions) returns true
        Note over Client: signState(state) returns userSig

        Client->>Node: SubmitState(state, userSig)
        Note right of Node: GetLastState(userWallet, asset) returns currentState
        Note right of Node: EnsureNoOngoingTransitions()
        Note right of Node: ValidateStateTransition(currentState, state)
        Note right of Node: StoreEscrowChannel(escrow_channel)
        Note right of Node: StoreState(state)
        Node->>Client: Return node signature
        Note over Client: PackChannelDefinition(channelDef)
        Note over Client: PackState(channelId, state)
        Node->>EscrowChain: initiateEscrowWithdrawal(packedChannelDef, packedState)
        EscrowChain->>Node: Return Tx Hash
        EscrowChain-->>Node: Emits EscrowWithdrawalInitiated Event
        Note right of Node: HandleEscrowWithdrawalInitiated()
        Note right of Node: UpdateEscrowChannel(escrow_channel)
        Node-->>Client: Sends ChannelUpdate & BalanceUpdate
        
        Client->>Node: GetLastState(UserWallet, asset)
        Note right of Node: GetLastState(userWallet, asset)
        Node->>Client: Returns state
        Note over Client: createNextState(currentState) returns state
        Note over Client: state.setID(CalculateStateID(state.userWallet, state.asset, state.cycleId, state.version))
        Note over Client: NewTransition(escrow_withdrawalT, state.ID(), escrowChannelID, amount)
        Note over Client: state.applyTransitions(transtions) returns true
        Note over Client: signState(state) returns userSig

        Client->>Node: SubmitState(state, userSig)
        Note right of Node: GetLastState(userWallet, asset) returns currentState
        Note right of Node: ValidateStateTransition(currentState, state)
        Note right of Node: StoreState(state)
        Node->>Client: Return node signature

        Note over Node: PackState(channelId, state)
        Client->>EscrowChain: finalizeEscrowWithdrawal(escrowChannelId, packedState)
        EscrowChain->>Client: Return Tx Hash
        EscrowChain-->>Node: Emits EscrowWithdrawalFinalized Event
        Note right of Node: HandleEscrowWithdrawalFinalized()
        Note right of Node: UpdateEscrowChannel(escrow_channel)
        Node-->>Client: Sends ChannelUpdate & BalanceUpdate
        