sequenceDiagram
        actor SenderUser
        actor SenderClient
        actor Node
        actor ReceiverClient
        
        Note over SenderClient: Connected to Node
        Note over Node: Contains user's state with Home Chain 

        SenderUser->>SenderClient: transfer(DestinationUserWallet, asset, amount)
        SenderClient->>Node: GetLastState(SenderUserWallet, asset)
        Note right of Node: GetLastState(userWallet, asset)
        Node->>SenderClient: Returns a state with home chain
        %% Note over SenderClient: Check current state transitions
        Note over SenderClient: createNextState(currentState) returns state
        Note over SenderClient: state.setID(CalculateStateID(state.userWallet, state.asset, cycleId, state.version))
        Note over SenderClient: NewTransition(transferT, state.ID(), DestinationSenderUserWallet, amount)
        Note over SenderClient: state.applyTransitions(transitions) returns true
        Note over SenderClient: signState(state) returns userSig

        SenderClient->>Node: SubmitState(state, userSig)
        Note right of Node: GetLastState(userWallet, asset) returns currentState
        Note right of Node: EnsureNoOngoingTransitions()
        Note right of Node: ValidateStateTransition(currentState, state)
        Note right of Node: StoreState(state)
        
        Note right of Node: CreateReceiverState(DestinationUserWallet)
        Note right of Node: GetLastState(DestinationUserWallet, asset)
        %% Note over SenderClient: Check current state transitions
        Note over Node: createNextState(receiver_state) returns new_receiver_state
        Note over Node: new_receiver_state.setID(CalculateStateID(new_receiver_state.userWallet, new_receiver_state.asset, cycleId, new_receiver_state.version))
        Note over Node: NewTransition(transfer_receiveT, new_receiver_state.ID(), DestinationUserWallet, amount)
        Note over Node: new_receiver_state.applyTransitions(transitions) returns true
        Note over Node: signState(new_receiver_state) returns nodeSig

        Node->>SenderClient: Sends ChannelUpdate & BalanceUpdate
        Node->>ReceiverClient: Sends ChannelUpdate & BalanceUpdate

        Node->>SenderClient: Return node signature

        SenderClient->>SenderUser: Returns success & tx hash
