{{- if .Values.debug.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clearnode.common.fullname" . }}-debug
  labels:
    {{- include "clearnode.common.labels" . | nindent 4 }}
    app.kubernetes.io/component: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clearnode.common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: debug
  template:
    metadata:
      labels:
        {{- include "clearnode.common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: debug
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ . }}
      {{- end }}
      containers:
        - name: debug
          image: {{ include "clearnode.component.image" .Values.image }}
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          env:
            {{- include "clearnode.common.env" . | nindent 12 }}
          {{- if or .Values.config.secretEnvs .Values.config.envSecret }}
          envFrom:
            {{- if .Values.config.envSecret }}
            - secretRef:
                name: {{ .Values.config.envSecret }}
            {{- end }}
            {{- if .Values.config.secretEnvs }}
            - secretRef:
                name: {{ include "clearnode.common.fullname" . }}-secret-env
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
            {{- if .Values.config.gcpSaSecret }}
            - name: gcp-sa
              mountPath: /etc/gcp
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.debug.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "clearnode.common.fullname" . }}-config
        {{- if .Values.config.gcpSaSecret }}
        - name: gcp-sa
          secret:
            secretName: {{ .Values.config.gcpSaSecret }}
        {{- end }}
      {{- include "clearnode.common.imagePullSecrets" . | nindent 6 }}
      {{- include "clearnode.common.nodeSelectorLabels" . | nindent 6 }}
      {{- include "clearnode.common.affinity" . | nindent 6 }}
      {{- include "clearnode.common.tolerations" . | nindent 6 }}
{{- end }}
