assets:
  - name: "yintegration.USD"
    symbol: "yintegration.usd"
    tokens:
      - blockchain_id: 31337
        address: "0xbD24c53072b9693A35642412227043Ffa5fac382"
        decimals: 6
  - name: "yintegration.ETH"
    symbol: "yintegration.eth"
    tokens:
      - blockchain_id: 31337
        address: "0xAf119209932D7EDe63055E60854E81acC4063a12"
        decimals: 18
