config:
  database:
    password: ref+tfstategs://terraform-state-deploy/gke-uat-postgresql-admin/default.tfstate/output.postgresql_user_passwords["clearnet_uat_admin"]
  secretEnvs:
    BROKER_PRIVATE_KEY: ref+gcpsecrets://ynet-stage/clearnet-uat-broker-private-key?version=latest
    POLYGON_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-uat-polygon-blockchain-rpc?version=latest
    ETHEREUM_SEPOLIA_BLOCKCHAIN_RPC: ref+gcpsecrets://ynet-stage/clearnet-uat-eth-sepolia-blockchain-rpc?version=latest
