name: SDK Non-Regression Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-deps-
    
    - name: Setup blockchain environment
      uses: ./.github/actions/setup-blockchain
    
    - name: Install SDK dependencies
      working-directory: ./sdk
      run: npm ci
    
    - name: Build SDK
      working-directory: ./sdk
      run: npm run build
    
    - name: Run integration tests
      working-directory: ./sdk
      run: npm run test:integration:coverage
      env:
        ANVIL_RPC_URL: http://localhost:8545
        CUSTODY_CONTRACT_ADDRESS: ${{ env.CUSTODY_CONTRACT_ADDRESS }}
        ADJUDICATOR_CONTRACT_ADDRESS: ${{ env.ADJUDICATOR_CONTRACT_ADDRESS }}
        TEST_TOKEN_CONTRACT_ADDRESS: ${{ env.TEST_TOKEN_CONTRACT_ADDRESS }}
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./sdk/coverage/lcov.info
        fail_ci_if_error: true

  golang-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Setup blockchain environment
      uses: ./.github/actions/setup-blockchain
    
    - name: Run Go tests
      working-directory: ./clearnode
      run: |
        go mod download
        go test -v -race -coverprofile=coverage.out ./...
      env:
        ETH_RPC_URL: http://localhost:8545
        CUSTODY_CONTRACT_ADDRESS: ${{ env.CUSTODY_CONTRACT_ADDRESS }}
        ADJUDICATOR_CONTRACT_ADDRESS: ${{ env.ADJUDICATOR_CONTRACT_ADDRESS }}
        TEST_TOKEN_CONTRACT_ADDRESS: ${{ env.TEST_TOKEN_CONTRACT_ADDRESS }}
    
    - name: Upload Go coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./clearnode/coverage.out
        fail_ci_if_error: true
