name: SDK Non-Regression Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./sdk/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Setup blockchain environment
        id: blockchain
        uses: ./.github/actions/setup-blockchain

      - name: Install SDK dependencies
        working-directory: ./sdk
        run: npm ci

      - name: Build SDK
        working-directory: ./sdk
        run: npm run build

      - name: Run integration tests
        working-directory: ./sdk
        run: npm run test:integration:coverage
        env:
          ANVIL_RPC_URL: http://127.0.0.1:8545
          CUSTODY_CONTRACT_ADDRESS: ${{ steps.blockchain.outputs.custody-address }}
          ADJUDICATOR_CONTRACT_ADDRESS: ${{ steps.blockchain.outputs.adjudicator-address }}
          TEST_TOKEN_CONTRACT_ADDRESS: ${{ steps.blockchain.outputs.token-address }}

  golang-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup blockchain environment
        id: blockchain-go
        uses: ./.github/actions/setup-blockchain

      - name: Run Go tests
        working-directory: ./clearnode
        run: |
          go mod download
          go test -v -race -coverprofile=coverage.out ./...
        env:
          ETH_RPC_URL: http://127.0.0.1:8545
          CUSTODY_CONTRACT_ADDRESS: ${{ steps.blockchain-go.outputs.custody-address }}
          ADJUDICATOR_CONTRACT_ADDRESS: ${{ steps.blockchain-go.outputs.adjudicator-address }}
          TEST_TOKEN_CONTRACT_ADDRESS: ${{ steps.blockchain-go.outputs.token-address }}
